id: rgbd_synthia 
models: 
    rgb:
        arch: DeepLab
        backbone: resnet101
        resume:  ./checkpoint/synthia-seq/deeplab/unweighted/rgb/rgb_DeepLab_synthia_best_model.pkl 
    d:
        arch: DeepLab
        backbone: resnet101
        resume: ./checkpoint/synthia-seq/deeplab/unweighted/d/d_DeepLab_synthia_best_model.pkl 
        

uncertainty: False 
imbalance:   
    beta: #0.4 
fusion: Noisy-Or  #Noisy-Or SoftmaxAverage, SoftmaxMultiply

save_stats: False
save_dir: ./
data:
    dataset: synthia
    train_split: train
    train_subsplit: ['SYNTHIA-SEQS-05-DAWN',
                   'SYNTHIA-SEQS-05-SUMMER',
                   'SYNTHIA-SEQS-05-NIGHT', 
                   'SYNTHIA-SEQS-05-SUNSET',]
    train_reduction: 1.0
    val_split: val # val
    val_subsplit: [
                  'SYNTHIA-SEQS-05-DAWN',
                  'SYNTHIA-SEQS-05-SUMMER',
                  'SYNTHIA-SEQS-05-NIGHT', 
                  'SYNTHIA-SEQS-05-SUNSET',
                  # 'SYNTHIA-SEQS-05-FOG',
                  # 'SYNTHIA-SEQS-05-SPRING',
                  # 'SYNTHIA-SEQS-05-FALL',
                  # 'SYNTHIA-SEQS-05-WINTER',
                  # 'SYNTHIA-SEQS-05-WINTERNIGHT',
                  # 'SYNTHIA-SEQS-05-RAIN',
                  # 'SYNTHIA-SEQS-05-RAINNIGHT',
                  # 'SYNTHIA-SEQS-05-SOFTRAIN',
                  ]    
    val_reduction: 1.0
    img_rows: 768
    img_cols: 384
    path: /datasets/synthia-seq/ 
    noisy_type: None 
training:
    weight: None
    train_iters: 100000
    batch_size: 4 
    val_interval: 10000 
    save_iters: 10000
    n_workers: 6
    print_interval: 5
    png_frames: 5 
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: None
