id: rgb_BayesianSegnet_0.5
model:
    arch: segnet_mcdo
models:
    rgb:
        in_channels: 3
        start_layer: down1
        end_layer: up1
        reduction: 1.0
        mcdo_passes: 1
        dropoutP: 0.5
        mcdo_start_iter: 0
        mcdo_backprop: False
        learned_uncertainty: "no"
        resume: None #models/rgb_BayesianSegnet_p0.1/rgb_segnet_mcdo_airsim_best_model.pkl #runs/segnet_airsim_normal/83811/rgb_segnet_airsim_best_model.pkl #None
    # d:
    #     in_channels: 3
    #     start_layer: down1
    #     end_layer: up1
    #     reduction: 1.0
    #     mcdo_passes: 5
    #     dropoutP: 0.5
    #     mcdo_start_iter: 0
    #     mcdo_backprop: False
    #     learned_uncertainty: "no"
    #     resume: models/d_0.5/d_segnet_mcdo_airsim_best_model.pkl #runs/segnet_airsim_normal/83811/rgb_segnet_airsim_best_model.pkl #None
fusion: None #{None,scores_variance_weighted, scores_even_weighted, softmax_variance_weighted, softmax_even_weighted}
data:
    dataset: airsim
    train_split: train
    train_subsplit: ['async_fog_000_clear']
    train_reduction: 1.0    
    val_split: val
    val_subsplit: [
                   'async_fog_000_clear',
                   'async_fog_050_clear',
                   'async_fog_100_clear',
                   "async_fog_100_clear__{'channel':'rgb','type':'blackoutNoise','value':'20'}",
                   "async_fog_100_clear__{'channel':'d','type':'blackoutNoise','value':'20'}",
                   "async_fog_100_clear__{'channel':'rgbd','type':'blackoutNoise','value':'20'}",                   
                  ]    
    val_reduction: 1.0
    img_rows: 512
    img_cols: 512
    path: ../../ros/data/airsim_03-30-2019/airsim_data_async
    noisy_type: None 
training:
    train_iters: 100000
    batch_size: 2
    val_interval: 5000
    n_workers: 8
    print_interval: 50
    png_frames: 5000
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: None