model:
    arch: segnet
    communication: single
data:
    dataset: airsim
    train_split: train
    train_subsplit: ['8camera_fog_000_dense', '8camera_rain_dense']    
    val_split: val
    img_rows: 512
    img_cols: 512
    path: /home/n8k9/ripl/ros/data/multi_view_seg
    noisy_type: occlusion 
training:
    train_iters: 80000
    batch_size: 2
    val_interval: 1000
    n_workers: 16
    print_interval: 50
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: None

