seed: 1337
id: rgb_deeplab_T000
model:
    arch: DeepLab
models:
    rgb:
        in_channels: 3
        resume: None #models/BayesianSegnet/rgb_BayesianSegnet_0.5_T000/rgb_segnet_mcdo_airsim_best_model.pkl       
full_mcdo: False #{True:AllLayersMCDO,False:BayesianSegnet}
fusion: None #{None,SoftmaxMultiply}
recal: None #{None,afterMcdo,beforeMcdo}
recalibrator: None #{Histogram,Polynomial_X}
temperatureScaling: False
bins: 1
data:
    dataset: airsim
    train_split: train
    train_subsplit: ['async_fog_000_clear']
    train_reduction: 1.0    
    recal_split: recal
    recal_subsplit: ['async_fog_000_clear']
    recal_reduction: 0.1
    val_split: val
    val_subsplit: [
                   'async_fog_000_clear',
                  ]    
    val_reduction: 0.5
    img_rows: 512
    img_cols: 512
    path: datasets/airsim_data_async #../../ros/data/airsim_03-30-2019/airsim_data_async
    noisy_type: None
training:
    train_iters: 100000
    batch_size: 2
    val_interval: 5000
    n_workers: 8
    print_interval: 50
    png_frames: 50
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: None