id: "MAGNUS_reweightedLoss"
model:
    arch: pspnet
############
# BASELINE #
############
# start_layers: None
# models:
#     input_fusion:
#         in_channels: 6 #if receiving mean and variance from input legs
#         # start_layer: res_block5 #res_block3 #res_block2
#         # end_layer: classification        
#         reduction: 0.5
#         mcdo_passes: 1
#         dropoutP: 0.1        
#         mcdo_start_iter: 0
#         mcdo_backprop: None
#         learned_uncertainty: "no"        
#         resume: None   
######################
# Middle Fusion MCDO #
######################
# learned_uncertainty: mode block needs to be "yes" followed by "double_input" fusion block
start_layers: [convbnrelu1_1,res_block3] #,res_block4]
models:
    rgb:
        in_channels: 3
        # start_layer: res_block2
        # end_layer: res_block4
        reduction: 0.5
        mcdo_passes: 5
        dropoutP: 0.1
        mcdo_start_iter: 0
        mcdo_backprop: False
        learned_uncertainty: "no"
        resume: None #models/rgb_only_pspnet_airsim_best_model.pkl
    d:
        in_channels: 3
        # start_layer: res_block2
        # end_layer: res_block4
        reduction: 0.5
        mcdo_passes: 5
        dropoutP: 0.1
        mcdo_start_iter: 0
        mcdo_backprop: False
        learned_uncertainty: "no"        
        resume: None #models/d_only_pspnet_airsim_best_model.pkl
    fuse:
        in_channels: -1
        # start_layer: res_block5 #res_block3 #res_block2
        # end_layer: classification        
        reduction: 0.5
        mcdo_passes: 1
        dropoutP: 0.1
        mcdo_start_iter: None
        mcdo_backprop: None
        learned_uncertainty: "no"        
        resume: None #models/rgb_only_pspnet_airsim_best_model.pkl
########################
# Isolated MCDO Fusion #
########################
# start_layers: [convbnrelu1_1,res_block2,res_block3]
# models:
#     rgb_static:
#         in_channels: 3
#         # start_layer: convbnrelu1_1
#         # end_layer: convbnrelu1_3
#         reduction: 0.5
#         mcdo_passes: 1
#         dropoutP: 0.1        
#         mcdo_start_iter: None
#         mcdo_backprop: None
#         learned_uncertainty: "no"        
#         resume: None     
#     d_static:
#         in_channels: 3
#         # start_layer: convbnrelu1_1
#         # end_layer: convbnrelu1_3
#         reduction: 0.5
#         mcdo_passes: 1
#         dropoutP: 0.1        
#         mcdo_start_iter: 0
#         mcdo_backprop: None
#         learned_uncertainty: "no"        
#         resume: None     
#     rgb:
#         in_channels: -1
#         # start_layer: res_block2
#         # end_layer: res_block4
#         reduction: 0.5
#         mcdo_passes: 5
#         dropoutP: 0.1        
#         mcdo_start_iter: 0
#         mcdo_backprop: False
#         learned_uncertainty: "no"
#         resume: None        
#     d:
#         in_channels: -1
#         # start_layer: res_block2
#         # end_layer: res_block4
#         reduction: 0.5
#         mcdo_passes: 5
#         dropoutP: 0.1        
#         mcdo_start_iter: 0
#         mcdo_backprop: False
#         learned_uncertainty: "no"        
#         resume: None
#     fuse:
#         in_channels: -1
#         #in_channels: 0 #if receiving mean and variance from input legs
#         #in_channels: 1 #if receiving mean and variance mask from input legs
#         #in_channels: -1 #if receiving output from input legs
#         # start_layer: res_block5 #res_block3 #res_block2
#         # end_layer: classification        
#         reduction: 0.5
#         mcdo_passes: 1
#         dropoutP: 0.1        
#         mcdo_start_iter: None
#         mcdo_backprop: None
#         learned_uncertainty: "no"        
#         resume: None   
data:
    dataset: airsim
    path: ../../ros/data/airsim_03-05-2019/airsim_data
    train_split: train
    train_subsplit: ['8camera_fog_000_dense','8camera_fog_050_dense']
    train_reduction: 1.0
    val_split: val
    val_subsplit: [
                   '8camera_fog_000_dense',
                   '8camera_fog_050_dense',
                   '8camera_fog_100_dense',
                   '8camera_rain_dense',
                   '8camera_fog_100_dense__rgb_blackoutNoiseMag20',
                   '8camera_fog_100_dense__depth_blackoutNoiseMag20',
                  ]    
    val_reduction: 1.0
    img_rows: 128 #512
    img_cols: 128 #512
training:
    train_iters: 300000
    batch_size: 8
    val_interval: 1000
    png_frames: 50
    n_workers: 16
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'multi_scale_cross_entropy'
        size_average: False
    lr_schedule:
