id: "" #mcdo_pretrain_256px_train_all_test_all_01-16-2019
model:
    arch: pspnet
model_params:
    variant: input_fusion #input_fusion #mcdo #1pass
    reduction: 1.0
    mcdo_passes: 5
models:
    rgb:
        in_channels: 3
        start_layer: convbnrelu1_1
        end_layer: res_block5
        reduction: 1.0
        mcdo_passes: 5
        resume: None        
    d:
        in_channels: 3
        start_layer: convbnrelu1_1
        end_layer: res_block5        
        reduction: 1.0
        mcdo_passes: 5        
        resume: None
    fuse:
        in_channels: 8192
        start_layer: pyramid_pooling
        end_layer: classification        
        reduction: 1.0
        mcdo_passes: 1
        resume: None
data:
    dataset: airsim
    path: ../../ros/data/airsim
    train_split: train
    train_subsplit: ["fog_000","fog_005","fog_010","fog_020"] #,"fog_025", "fog_050","fog_100"]
    val_split: val
    img_rows: 128 #512
    img_cols: 128 #512
training:
    train_iters: 200000
    batch_size: 2 
    val_interval: 1000
    n_workers: 16
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'multi_scale_cross_entropy'
        size_average: False
    lr_schedule:
    resume: models/pspnet_airsim_default_fixed_segmentation_01-11-2019.pkl
    resumeRGB: None #models/pspnet_airsim_rgb_fog_all_01-16-2019.pkl
    resumeD: None #models/pspnet_airsim_depth_fog_all_01-16-2019.pkl
