id: rgbd_uno++_airsim #rgbd_NoisyOr_SSMA_RGB_D #rgbd_NoisyOr_T000+T050_pretrain_1_val #rgbd_NoisyOr_T000+T050_val # rgbd_Compnet_T000+T050_val
models:
    rgb:
        arch: segnet_mcdo
        in_channels: 3
        start_layer: down1
        end_layer: up1
        reduction: 1.0
        mcdo_passes: 1 # Number of Passes
        dropoutP: 0 # Dropout Probability
        resume: /home/jtian73/pytorch-semseg/checkpoint/airsim_icra/rgb/rgb_segnet_mcdo_airsim_best_model.pkl  #/home/jtian73/fusion_backup/runs/configs/experiments/icra_configs/rgbd_TempNet_T000+T050_pretrain_1/rgb_tempnet_airsim_100000_model.pkl
    d:
        arch: segnet_mcdo
        in_channels: 3
        start_layer: down1
        end_layer: up1
        reduction: 1.0
        mcdo_passes: 1 # Number of Passes
        dropoutP: 0 # Dropout Probability
        resume: /home/jtian73/pytorch-semseg/checkpoint/airsim_icra/d/d_segnet_mcdo_airsim_best_model.pkl #/home/jtian73/fusion_backup/runs/configs/experiments/icra_configs/rgbd_TempNet_T000+T050_pretrain_1/d_tempnet_airsim_100000_model.pkl
    rgbd:
        arch: SSMA
        backbone: segnet
        resume: /home/jtian73/pytorch-semseg/checkpoint/airsim_icra/rgbd/rgbd_SSMA_airsim_best_model.pkl #/home/jtian73/fusion_backup/runs/configs/experiments/fusion/SSMA/SSMA_T000+T050/best_model/rgbd_SSMA_airsim_best_model.pkl
   
fusion: Noisy-Or  #Noisy-Or   #Stacked-Noisy-Or  #Noisy-Or # #{None,SoftmaxMultiply}
scaling_module: None #GlobalScaling #GlobalScaling
scaling_metrics: SoftEn #Mixed #AveTemp  #SoftEn #MI 
save_stats: False
data:
    dataset: airsim
    train_split: train
    train_subsplit: ['async_fog_000_clear']
    train_reduction: 1.0    
    val_split: val
    val_subsplit: [
                   'async_fog_000_clear',
                   'async_fog_050_clear',
                   'async_fog_100_clear',
                   #"async_fog_000_clear__{'channel':'rgb','type':'defocusBlur','value':'3'}",
                   #"async_fog_000_clear__{'channel':'rgb','type':'glassBlur','value':'3'}",
                   "async_fog_000_clear__{'channel':'rgb','type':'motionBlur','value':'3'}",
                   #"async_fog_000_clear__{'channel':'rgb','type':'zoomBlur','value':'3'}",
                   "async_fog_000_clear__{'channel':'rgb','type':'snow','value':'3'}",
                   "async_fog_000_clear__{'channel':'rgb','type':'frost','value':'3'}",
                   #"async_fog_000_clear__{'channel':'rgb','type':'fog','value':'3'}",
                   "async_fog_000_clear__{'channel':'rgb','type':'brightness','value':'3'}",
                   #"async_fog_000_clear__{'channel':'rgb','type':'contrast','value':'3'}",
                   #"async_fog_000_clear__{'channel':'rgb','type':'elastic','value':'3'}",
                   # "async_fog_000_clear__{'channel':'rgb','type':'pixelate','value':'3'}",
                   # "async_fog_000_clear__{'channel':'rgb','type':'jpeg','value':'3'}",
                   "async_fog_000_clear__{'channel':'rgb','type':'blackoutNoise','value':'20'}",
                   "async_fog_000_clear__{'channel':'rgb','type':'impulseNoise','value':'3'}",
                   "async_fog_000_clear__{'channel':'d','type':'gaussianNoise','value':'3'}",
                   "async_fog_000_clear__{'channel':'d','type':'shotNoise','value':'3'}",
                   "async_fog_000_clear__{'channel':'d','type':'impulseNoise','value':'3'}",
                   #"async_fog_000_clear__{'channel':'d','type':'blackoutNoise','value':'20'}",
                  ]   
    val_reduction: 1.0
    img_rows: 512
    img_cols: 512
    path: /home/jtian73/datasets/airsim_03-30-2019/airsim_data_async ##datasets/airsim_data_async #../../ros/data/airsim_03-30-2019/airsim_data_async
    noisy_type: None 
training:
    weight: None
    train_iters: 100000
    batch_size: 2
    val_interval: 10000 #5000
    save_iters: 10000
    n_workers: 4
    print_interval: 50
    png_frames: 50 #5000
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: None

training_stats: 
    MI_MEAN_rgb: 0.01635716
    MI_STD_rgb: 0.00688986
    PreEn_MEAN_rgb: 0.16158119
    PreEn_STD_rgb: 0.03454985
    SoftEn_MEAN_rgb: 0.10871122
    SoftEn_STD_rgb: 0.02284632

    MI_MEAN_d: 0.02271291
    MI_STD_d: 0.01019019
    PreEn_MEAN_d: 0.20687151
    PreEn_STD_d: 0.04621102
    SoftEn_MEAN_d: 0.13952574
    SoftEn_STD_d: 0.03168533

    SoftEn_MEAN_rgbd: 0.05217332
    SoftEn_STD_rgbd: 0.01356846
