seed: 1337
id: BayesianSegnet_tempScaling_T100
model:
    arch: segnet_mcdo
models:
    d:
        in_channels: 3
        start_layer: down1
        end_layer: up1
        freeze_seg: True
        reduction: 1.0
        mcdo_passes: 6
        mask_dir: models/DropoutMasks/Random 
        masks: [0,1,2,3,4,5] 
        fixed_mcdo: No
        dropoutP: 0.5
        resume: models/Segnet/d_Segnet/d_segnet_mcdo_airsim_T100.pkl
fusion: None #{None,SoftmaxMultiply}
recal: None #{None,afterMCDO,beforeMCDO}
recalibrator: None #{Histogram,Polynomial_X}
temperatureScaling: True
bins: 20
data:
    dataset: airsim
    train_split: train
    train_subsplit: ['async_fog_100_clear']
    train_reduction: 1.0    
    recal_split: recal
    recal_subsplit: ['async_fog_100_clear']
    recal_reduction: 0.5
    val_split: val
    val_subsplit: [
                   'async_fog_100_clear',
                  ]    
    val_reduction: 0.5
    img_rows: 512
    img_cols: 512
    path: datasets/airsim_data_async #../../ros/data/airsim_03-30-2019/airsim_data_async
    noisy_type: None 
training:
    train_iters: 100000
    batch_size: 2
    val_interval: 5000
    n_workers: 8
    print_interval: 50
    png_frames: 50
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: None
