id: BayesianSegnet_tempScaling_T100
model:
    arch: segnet_mcdo
models:
    rgb:
        in_channels: 3
        start_layer: down1
        end_layer: up1
        reduction: 1.0
        mcdo_passes: 6 # Number of Passes
        mask_dir: models/DropoutMasks/Random # Directory of Indexed Masks
        masks: [0,1,2,3,4,5] # Number Mask Indices Should Equal Number of MCDO Passes
        fixed_mcdo: No # Yes: Fixed Masks per Pass; No: Randomized Masks per Pass
        dropoutP: 0.5 # Dropout Probability
        resume: None
    d:
        in_channels: 3
        start_layer: down1
        end_layer: up1
        reduction: 1.0
        mcdo_passes: 6
        mask_dir: models/DropoutMasks/Random 
        masks: [0,1,2,3,4,5] 
        fixed_mcdo: No
        dropoutP: 0.5
        resume: None
fusion: None #{None,SoftmaxMultiply}
recal: None #{None,afterMCDO,beforeMCDO}
recalibrator: TemperatureScaling #{Histogram,Polynomial_X}
bins: 20
data:
    dataset: airsim
    train_split: train
    train_subsplit: ['async_fog_100_clear']
    train_reduction: 1.0    
    recal_split: recal
    recal_subsplit: ['async_fog_100_clear']
    recal_reduction: 0.5
    val_split: val
    val_subsplit: [
                   'async_fog_000_clear',
                   'async_fog_050_clear',
                   'async_fog_100_clear',
                   "async_fog_100_clear__{'channel':'rgb','type':'blackoutNoise','value':'20'}",
                   "async_fog_100_clear__{'channel':'d','type':'blackoutNoise','value':'20'}",
                   "async_fog_100_clear__{'channel':'rgbd','type':'blackoutNoise','value':'20'}",                   
                  ]    
    val_reduction: 1.0
    img_rows: 512
    img_cols: 512
    path: datasets/airsim_data_async #../../ros/data/airsim_03-30-2019/airsim_data_async
    noisy_type: None 
training:
    train_iters: 100000
    batch_size: 2
    val_interval: 50000
    n_workers: 8
    print_interval: 1000
    png_frames: 5000
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: None
