id: rgb_airsim_segnet_T000
models:
    rgb:
        arch: segnet_mcdo
        in_channels: 3
        start_layer: down1
        end_layer: up1
        mcdo_passes: 1
        dropoutP: 0.5
        full_mcdo: False
        reduction: 1.0
        resume: None

data:
    dataset: airsim
    train_split: train
    train_subsplit: ['async_fog_000_clear']
    train_reduction: 1.0 
    val_split: val
    val_subsplit: ['async_fog_000_clear']
    val_reduction: 0.5
    img_rows: 512
    img_cols: 512
    path: /home/jtian73/datasets/airsim_03-30-2019/airsim_data_async #../../ros/data/airsim_03-30-2019/airsim_data_async
    noisy_type: None

training:
    seed: 1337
    weight: [32.93554, 575.20610, 4.87791, 1.0, 21.79751, 204.85757, 4.60879, 8.74993, 81.57046412795533, 41.01965, 7.37522]
    train_iters: 500000
    batch_size: 2
    val_interval: 10000 #5000
    n_workers: 4
    print_interval: 50
    png_frames: 50 #5000
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume_iteration: False
